# Generated by Django 6.0.5 on 2026-06-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_key', models.CharField(db_index=True, max_length=128)),
                ('x', models.IntegerField(db_index=True)),
                ('y', models.IntegerField(db_index=True)),
                ('overlay_type', models.CharField(db_index=True, max_length=64)),
                ('object_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_permanent', models.BooleanField(default=True)),
                ('blocks_cleanup', models.BooleanField(default=True)),
                ('visible_on_surface', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['planet_key', 'x', 'y'], name='surface_sur_planet__47e0f3_idx'), models.Index(fields=['planet_key', 'overlay_type'], name='surface_sur_planet__3db301_idx'), models.Index(fields=['object_id'], name='surface_sur_object__e79a49_idx'), models.Index(fields=['owner_id'], name='surface_sur_owner_i_40e905_idx')],
            },
        ),
    ]
